=== jommen/trier_fm_vis/src/de/hochschuleTrier/fmv/io/complexConstraints/complexConstraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="complexConstraints" 
	xmlns:tns="complexConstraints" 
	elementFormDefault="qualified">
	
	<!-- ROOT-Element -->	
	<xsd:element name="complexConstraints" id="complexConstraints"> 
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="implies" type="tns:constraintGroup" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="excludes" type="tns:constraintGroup" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType> 
	</xsd:element>
	
	<!-- Andere Elemente -->	
	<xsd:complexType name="constraintGroup" mixed="true">
		<xsd:sequence minOccurs="1">
			<xsd:element name="node" type="tns:node" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="and" type="tns:constraint" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="or" type="tns:constraint" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="constraint" mixed="true">
		<xsd:sequence minOccurs="1">
			<xsd:element name="node" type="tns:node" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="and" type="tns:constraint" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="or" type="tns:constraint" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="negate" type="xsd:boolean" />
	</xsd:complexType>
	
	<xsd:complexType name="node">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="negate" type="xsd:boolean" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
</xsd:schema>

=== jommen/trier_fm_vis/src/de/hochschuleTrier/fmv/io/complexConstraints/complexConstraints.xml
<?xml version="1.0" ?>
<complexConstraints xmlns="complexConstraints"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="complexConstraints complexConstraints.xsd">
	<implies>
		<and>
			<node>Z</node>
			<node>Y</node> 
			<or>
				<node>A</node>
				<node negate="true">B</node>
			</or>
		</and>
		<or negate="true">
			<node>C</node>
			<node>D</node>
		</or>
	</implies>
</complexConstraints>
